Algoritmo "03_EXERCICIO"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Naiara Santiago
// Data atual  : 26/08/2021
Var
altura, base, area: real


Inicio
Escreval ("LEITURA DE ÁREA")
Escreva ("Qual a altura do retângulo? ")
Leia (altura)
Escreva ("Qual a base do retângulo? ")
Leia (base)
area<-(altura*base)
Escreval ("A área do retângulo é: ", area)


Fimalgoritmo