Algoritmo "04_exercicio"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Naiara Santiago
// Data atual  : 26/08/2021
Var
area, raio : real


Inicio
Escreval ("LENDO O RAIO DE UM CÍRCULO")
Escreva ("Informe o raio de uma circunferência: ")
Leia(raio)
area := pi*quad(raio)
Escreva("A Área da circunferência é: ", area:3:3, "cm²")


Fimalgoritmo