Algoritmo "ENQUANTO07"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Naiara Santiago
// Data atual  : 10/09/2021
Var

cont, valor1, valor2, valor3: Inteiro


Inicio

cont <- 1
valor1<-(-1)
valor2<-1

Enquanto cont <=15 faca
valor3<- valor1+valor2
valor1<-valor2
valor2<-valor3
Escreva(valor3)
cont<-cont+1

   Fimenquanto

Fimalgoritmo