Algoritmo "ENQUANTO10"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Naiara Santiago
// Data atual  : 10/09/2021
Var

cont, soma : Inteiro
media : Real


Inicio

cont<-50
soma<-0

Enquanto (cont<=70) faca
Se cont%2=0 entao
soma<-soma+cont

Fimse
media<-(soma/11)
cont<-cont+1

      Fimenquanto

Escreval ("A soma de todos os números pares será: ", soma)
Escreval ("A média dos números pares será: ", media)

Fimalgoritmo