Algoritmo "ENQUANTO12"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Naiara Santiago
// Data atual  : 10/09/2021
Var

num, X, Y : Inteiro

Inicio

Enquanto num >= 0 faca
Escreva ("Digite um valor: ")
Leia (num)
Se num < 0 entao
X <- num
senao
Se num > Y entao
Y <- num
Fimse
Fimse

Fimenquanto

   Escreval ("O maior valor digitado foi: ", Y)
   Escreval ("O menor valor digitado foi: ", X)

Fimalgoritmo