Algoritmo "enquanto03"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Naiara Santiago
// Data atual  : 03/09/2021
Var

num, pares, soma : Inteiro


Inicio

num<-0
pares<-0
soma<-0

Enquanto num<=500 faca
num<-num+1

Se num%2=0 entao
pares<-num
soma<-soma+pares

Fimse
Fimenquanto
Escreva ("A soma dos valores pares de 1 - 500 é de: ", soma)

Fimalgoritmo