Algoritmo "ENQUANTO08"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2021
Var

cont : Inteiro
temp_F : Real


Inicio

cont<-10
Enquanto cont <=100 faca
temp_F<- ((9*cont)+160)/5

Escreval ("A temperatura em Celsius é: ", cont, " e em Fahrenheit é: ", temp_F)
cont<-cont+10

   Fimenquanto

Fimalgoritmo