Algoritmo "Enquanto04"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Naiara Sntiago
// Data atual  : 03/09/2021
Var

num, impares : Inteiro


Inicio

num <- 0
impares <- 0
Escreval ("Os valores ímpares entre 0 - 20, são: ")
Enquanto num <= 20 faca
Se num%2=1 entao
impares <- num
Escreva(num)

Fimse
num <- num + 1

Fimenquanto

Fimalgoritmo