Algoritmo "ENQUANTO05"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Naiara Santiago
// Data atual  : 03/09/2021
Var

potencia, resultado : Inteiro


Inicio

potencia<- 0
resultado<- 1
Enquanto potencia <= 15 faca
Escreval ("O número 3 elevado a ",potencia, " será: ",resultado)
potencia <- potencia + 1
resultado <- resultado * 3

   Fimenquanto

Fimalgoritmo