Algoritmo "01"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Naiara Santiago
// Data atual  : 10/09/2021
Var


cont, X, R: Inteiro


Inicio

Para cont de 1 ate 5 passo 1 faca
Escreva ("Digite um número para X: ")
Leia (X)
R<- X * 3
Escreval ("O resultado da multiplicação de X por 3 é: ", R)
Escreval ("------------------")

FimPara


Fimalgoritmoo