Algoritmo "APRENDIZAGEM"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Naiara Santiago
// Data atual  : 10/09/2021
Var

fatorial, contador, num : Inteiro


Inicio

fatorial<-1
Escreva ("Escolha um número para fazer o fatorial: ")
Leia (num)
Para contador de 1 ate num passo 1 faca
fatorial<-fatorial*contador

FimPara

Escreva ("O fatorial de ", contador, " será: ", fatorial)

Fimalgoritmo