Algoritmo "Demonstração_Para"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Naiara Santiago
// Data atual  : 10/09/2021
Var

cont, cont1 : Inteiro
resp : Real

Inicio

Para cont de 1 ate 10 passo 2 faca
Escreval (cont)
Escreval ("")
Para cont1 de 2 ate 10 passo 2 faca
Escreval (cont1)
Escreval ("")

FimPara
FimPara

Fimalgoritmo