Algoritmo "EX-6"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Naiara Santiago
// Data atual  : 11/09/2021
Var

cont, divi : Inteiro


Inicio

cont<-1
Escreval ("Os número que podem ser divididos por 4 dentro de 0 a 200 são: ")
Para cont de 1 ate 200 passo 1 faca
Se cont%4=0 entao
divi<-cont
Escreval (divi)
FimSe
FimPara


Fimalgoritmo