Algoritmo "EX-7"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Naiara Santiago
// Data atual  : 11/09/2021
Var

potencia, resultado: Inteiro


Inicio

resultado<- 1
Para potencia de 0 ate 15 passo 1 faca
potencia<-potencia+1
resultado<-resultado*3
Escreval ("O resultado de 3 elevado a ", potencia, " = ", resultado)

FimPara

Fimalgoritmo