Algoritmo "EX-C"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Naiara Santiago
// Data atual  : 09/09/2021
Var

cont, num : Inteiro

Inicio

cont<-1
num<-0
Escreval ("Os números divisíveis por 4 entre 1 e 200, são: ")
Escreval ("")
Repita
Se (num%4=0) entao
Escreva (num, ", ")

      FimSe
      
num<-num+1
cont<-cont+1
Ate cont>201


Fimalgoritmo