Algoritmo "EX-I"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Naiara Santiago
// Data atual  : 11/09/2021
Var

valor, maior, menor : Inteiro

Inicio

Repita
Escreva ("Digite um valor: ")
Leia (valor)
Se valor > maior entao
maior<-valor

senao
Se valor < menor entao
menor <- valor

FimSe
FimSe

Ate valor<0
Escreval ("O maior valor informado foi: ", maior)
Escreval ("O menor valor informado foi: ", menor)

Fimalgoritmo