Algoritmo "REPITA-2"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Naiara Santiago
// Data atual  : 09/09/2021
Var

X, R : Inteiro
resposta : Caractere


Inicio

Repita

Escreva ("Digite um valor para X: ")
Leia (X)
R <- X * 3
Escreval ("O valor de X multiplicado por 3 é: ", R)
Escreval ("")
Escreva ("Deseja continuar a calcular ? [ S ] ou [ N ]")
Escreval ("")
Leia (resposta)
Ate (resposta <> "S")

Fimalgoritmo