Algoritmo "19_exercicio"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Naiara Santaigo
// Data atual  : 31/08/2021
Var

n1, n2 : Inteiro


Inicio

Escreva ("Digite um valor: ")
Leia (n1)
Escreva ("Digite outro valor: ")
Leia (n2)

   Se n1 > n2 entao
   Escreva ("O maior número digitado foi: ", n1)

   Senao
Escreva ("O maior número digitado foi: ", n2)

   Fimse

Fimalgoritmo
© 2021 GitHub, Inc.