Algoritmo "20_exercicio"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Naiara Santaigo
// Data atual  : 31/08/2021
Var
n1, n2 : Inteiro


Inicio

Escreva ("Digite um valor: ")
Leia (n1)
Escreva ("Digite outro valor: ")
Leia (n2)

   Se n1 > n2 entao
      Escreval ("Em ordem crescente, temos: ", n2, ", ", n1, ".")

   Senao
      Escreval ("Em ordem crescente, temos: ", n1, ", ", n2, ".")

   Fimse



Fimalgoritmo