Algoritmo "27_exercicio"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Naiara Santiago
// Data atual  : 01/09/2021
Var

valor : Real


Inicio

Escreva ("DIGITE UM VALOR: ")
Leia (valor)

Se valor = 0 entao
Escreval ("O valor digitado é 0")

senao
Se valor > 0 entao
Escreval ("O valor digitado é positivo!")

senao
Escreval ("O valor digitado é negativo!")

      Fimse
   Fimse


Fimalgoritmo