Algoritmo "05_exercicio"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Naiara Santiago
// Data atual  : 26/08/2021
Var
valor1, result: real


Inicio
Escreval ("Calcular a área do quadrado")
Escreva ("Digite o valor das extremidades do quadrado: ")
Leia (valor1)
result<-quad(valor1)
Escreval ("A área do quadrado é: ", result, "cm²")


Fimalgoritmo