Algoritmo "06_exercicio"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Naiara Santiago
// Data atual  : 26/08/2021
Var
base, altura, area: real


Inicio
Escreval ("Calculando a área do Triangulo")
Escreva ("Digite o valor da base do triangulo: ")
Leia (base)
Escreva ("Digite a altura do triangulo: ")
Leia (altura)
area<-base*altura/2
Escreva ("A área do triângulo é: ", area)



Fimalgoritmo