Algoritmo "07_exercicio"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Naiara Santiago
// Data atual  : 27/08/2021
Var
idade, meses, dias: real


Inicio
Escreval ("Calculador de idade")
Escreva ("Digite sua idade: ")
Leia (idade)
Escreval ("Sua idade em ANOS é: ", idade)
meses<-idade*12
Escreval ("Sua idade em MESES é: ", meses)
dias<-idade*365
Escreval ("Sua idade em DIAS é: ", dias)


Fimalgoritmo