Algoritmo "1_Exercicio"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Naiara
// Data atual  : 25/08/2021
Var
// Seção de Declarações das variáveis
 Numero, Antecessor: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("ALGORITMO ANTECESSOR")
Escreva ("Escolha um Número: ")
Leia (Numero)
antecessor<-Numero-1
Escreval ("O antecessor ao número escolhido é: ", Antecessor)

Fimalgoritmo